window.ARCHITECTS = [
  {
    id: 'chinmay-patil',
    name: 'Chinmay Patil',
    initials: 'CP',
    gradientFrom: '#c5fb50',
    gradientTo: '#0ea5e9',
    role: 'Senior Software Engineer · 5–8 yrs',
    bio: 'Chinmay builds across the full stack — frontend, backend, APIs, and mobile — with a particular focus on the glue that AI-generated code tends to get wrong: the integration layer between services, the data model that won\'t survive a real migration, and the RAG retrieval patterns that quietly hallucinate under load. He reviews apps end-to-end and gives you a plain-language list of what to fix and in what order.',
    tags: ['Frontend', 'Backend', 'APIs', 'Mobile', 'RAG / Retrieval', 'Infrastructure'],
    main: ['engineering', 'ai-data'],
    subs: ['Frontend', 'Backend', 'APIs', 'LLM Integration', 'RAG / Retrieval'],
    turnaround: '3–5 days',
    focus: 'both',
    works: 'shout',
    linkedin: 'https://www.linkedin.com/in/chinmay-patil-/'
  },
  {
    id: 'dan-kowalski',
    name: 'Dan Kowalski',
    initials: 'DK',
    gradientFrom: '#dc2626',
    gradientTo: '#9333ea',
    role: 'Application Security Engineer · 13 yrs',
    bio: 'Dan ran AppSec at a payment processor where he found and disclosed three critical IDOR vulnerabilities before a public audit and built the secure-SDLC programme that replaced their ad-hoc pen-testing. He has seen every class of vulnerability that Cursor and Copilot tend to introduce — and can tell you in plain language what is dangerous versus what is just untidy.',
    tags: ['AppSec', 'Pen Testing', 'Auth / Identity', 'OWASP', 'Node.js'],
    main: ['security'],
    subs: ['AppSec', 'Auth / Identity', 'Pen Testing'],
    turnaround: '2–3 days',
    focus: 'rescues',
    works: 'paid',
    linkedin: 'https://linkedin.com/in/dan-kowalski'
  },
  {
    id: 'marcus-delgado',
    name: 'Marcus Delgado',
    initials: 'MD',
    gradientFrom: '#10b981',
    gradientTo: '#3b82f6',
    role: 'AI/ML Engineer · 8 yrs',
    bio: 'Marcus built the semantic search and recommendation pipeline at a legal-tech company processing 2 million documents a week, and led RAG system design at an enterprise AI startup funded by a16z. He routinely spots retrieval hallucination in naive RAG builds, chunking strategies that break at scale, and LLM integration patterns that quietly leak PII.',
    tags: ['LLMs', 'RAG', 'Python', 'Vector DBs', 'LangChain'],
    main: ['ai-data'],
    subs: ['LLM Integration', 'RAG / Retrieval', 'Agents'],
    turnaround: '3–5 days',
    focus: 'both',
    works: 'paid',
    linkedin: 'https://linkedin.com/in/marcus-delgado'
  },
  {
    id: 'sara-lindqvist',
    name: 'Sara Lindqvist',
    initials: 'SL',
    gradientFrom: '#06b6d4',
    gradientTo: '#6366f1',
    role: 'Senior Product Designer · 9 yrs',
    bio: 'Sara led product design at two B2B SaaS companies, most recently as the founding designer at a YC-backed workflow tool where she built the design system from zero. She reviews AI-generated interfaces for flow coherence, information hierarchy, and the subtle patronising copy that LLMs love to produce.',
    tags: ['Product Design', 'Figma', 'UX Research', 'Design Systems', 'B2B SaaS'],
    main: ['design'],
    subs: ['Product Design', 'UX Research', 'Design Systems'],
    turnaround: '4–6 days',
    focus: 'both',
    works: 'shout',
    linkedin: 'https://linkedin.com/in/sara-lindqvist'
  },
  {
    id: 'yuki-tanaka',
    name: 'Yuki Tanaka',
    initials: 'YT',
    gradientFrom: '#0ea5e9',
    gradientTo: '#10b981',
    role: 'Staff DevOps Engineer · 10 yrs',
    bio: 'Yuki built the CI/CD platform and Kubernetes infrastructure at a Series C healthtech company, reducing deploy times from 45 minutes to 8 and achieving SOC 2 Type II certification along the way. She reviews AI-generated infrastructure code for the things that only hurt you at 3am — missing readiness probes, hard-coded secrets in Dockerfiles, and IAM policies that are quietly wider than intended.',
    tags: ['Kubernetes', 'CI/CD', 'Terraform', 'AWS', 'GitHub Actions'],
    main: ['devops'],
    subs: ['CI/CD', 'Cloud Setup', 'Infrastructure'],
    turnaround: '3–4 days',
    focus: 'both',
    works: 'shout',
    linkedin: 'https://linkedin.com/in/yuki-tanaka'
  }
];
